# Generated by Django 3.0.3 on 2020-05-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
